### ISSUE TITLE
Add Interstate

### ISSUE THREAD

**Issue by pel-daniel** [pel-daniel/mind-bicyles#4]
Search the links of the project
Video: https://www.youtube.com/watch?v=M--9jsuDZis

**Comment by jnv** [comment]
There are links on [Steve Oney's homepage](http://from.so/):

- Homepage: http://interstate.from.so/
- Source: https://github.com/soney/interstate
- Paper: http://from.so/p/interstate.pdf

**Comment by pel-daniel** [comment]
Thanks for the links @jnv !
